kind: Pod
apiVersion: v1
metadata:
  name: job17-torch-vae
spec:
  restartPolicy: Never
  schedulerName: my-scheduler
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
  containers:
    - name: lenet-test-epoch
      image: fuyuqi1995/june-vae
      command: ["python"]
      args: ["app.py","15","/root/torch/job17-torch-vae.csv","job17-torch-vae"]
      volumeMounts:
      - mountPath: "/root/torch"
        name: task-pv-storage

