kind: Pod
apiVersion: v1
metadata:
  name: job29-torch-lenet
spec:
  restartPolicy: Never
  schedulerName: my-scheduler
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
  containers:
    - name: lenet-test-epoch
      image: fuyuqi1995/june-lenet
      command: ["python"]
      args: ["lenet.py","5","/root/torch/job29-torch-lenet.csv","job29-torch-lenet"]
      volumeMounts:
      - mountPath: "/root/torch"
        name: task-pv-storage

