kind: Pod
apiVersion: v1
metadata:
  name: job40-tf-birnn
spec:
  restartPolicy: Never
  schedulerName: my-scheduler
  volumes:
  - name: task-pv-storage
    persistentVolumeClaim:
      claimName: pvc1-nfs
  containers:
    - name: bi-rnn
      image: zsl3203/birnn_log
      command: ["python"]
      args: ["bi_rnn_log.py","10000","/root/birnn/job40-tf-birnn.csv","job40-tf-birnn"]
      volumeMounts:
      - mountPath: "/root/birnn/"
        name: task-pv-storage
